"""The two machine-readable contracts the launcher GUI depends on.

The GUI links no SDK and reads no disc itself: it spawns `thps_p8_identify` and
`thps_p8_launch --check --json` and renders what they say. That makes their
stdout an interface, and this file is the gate on it.

Both regressions these tests exist for were real and shipped:

* `thps_p8_identify` segfaulted on a disc image truncated after its header, so a
  truncated dump crashed instead of being refused. Release gate 8 in
  `docs/policies/dependency-licences.md` requires it to fail closed.
* The SDK logs to **stdout**, so `[error] [fs] ...` landed in the middle of the
  JSON. Every broken input produced unparseable output and the GUI only survived
  it by substring-matching rather than parsing.

Hence the shape of these tests: every case asserts `json.loads` succeeds on the
whole of stdout, not that some substring appears in it.

Nothing here touches the owner's disc image. The inputs are generated bytes, so
the suite is hermetic and runs in well under a second.
"""

from __future__ import annotations

import json
import subprocess
import zipfile
from pathlib import Path

import pytest


WORKSPACE = Path(__file__).resolve().parents[3]
IDENTIFY = WORKSPACE / "recomp" / "identify" / "out" / "thps_p8_identify"
LAUNCH = WORKSPACE / "recomp" / "build" / "out" / "build" / "relwithdebinfo" / "thps_p8_launch"

needs_identify = pytest.mark.skipif(
    not IDENTIFY.exists(), reason="thps_p8_identify not built (`make identify`)"
)
needs_launch = pytest.mark.skipif(
    not LAUNCH.exists(), reason="thps_p8_launch not built (`make build`)"
)


def _identify(path: Path | str) -> dict:
    """Run the worker and parse the whole of stdout as JSON.

    Deliberately not tolerant: if anything else reaches stdout this raises, which
    is the point. stderr is left alone -- diagnostics belong there.
    """
    result = subprocess.run(
        [str(IDENTIFY), f"--identify_disc={path}", "--json"],
        capture_output=True,
        text=True,
        timeout=120,
    )
    return json.loads(result.stdout)


@needs_identify
def test_missing_file_is_an_io_error(tmp_path: Path) -> None:
    assert _identify(tmp_path / "nothing-here.iso")["verdict"] == "IO_ERROR"


@needs_identify
def test_random_bytes_are_not_a_disc(tmp_path: Path) -> None:
    junk = tmp_path / "random.iso"
    junk.write_bytes(bytes(range(256)) * 4096)
    assert _identify(junk)["verdict"] == "NOT_A_DISC"


@needs_identify
def test_a_zip_is_not_a_disc(tmp_path: Path) -> None:
    archive = tmp_path / "notagame.zip"
    with zipfile.ZipFile(archive, "w") as handle:
        handle.writestr("hello.txt", "not a disc")
    assert _identify(archive)["verdict"] == "NOT_A_DISC"


@needs_identify
def test_a_directory_is_not_a_disc(tmp_path: Path) -> None:
    folder = tmp_path / "some-folder"
    folder.mkdir()
    assert _identify(folder)["verdict"] == "NOT_A_DISC"


@needs_identify
def test_empty_file_is_refused_not_crashed(tmp_path: Path) -> None:
    """A zero-byte file is the cheapest truncation there is.

    The guard being exercised is the forked parse: whatever the SDK does to
    malformed input, this program must still emit a verdict rather than die on a
    signal. `json.loads` failing here means the crash containment regressed.
    """
    empty = tmp_path / "empty.iso"
    empty.touch()
    assert _identify(empty)["verdict"] in {"NOT_A_DISC", "IO_ERROR"}


@needs_identify
def test_never_writes_anything_when_only_identifying(tmp_path: Path) -> None:
    """Identity must not have side effects: it runs before the user has agreed
    to anything, and on a file we may be about to reject."""
    junk = tmp_path / "random.iso"
    junk.write_bytes(b"\x00" * 8192)
    before = sorted(p.name for p in tmp_path.iterdir())
    _identify(junk)
    assert sorted(p.name for p in tmp_path.iterdir()) == before


@needs_launch
def test_check_json_is_parseable_and_shaped() -> None:
    """The three home-screen states are derived from these fields, so their
    presence is the contract -- not their values, which depend on the machine."""
    result = subprocess.run(
        [str(LAUNCH), "--check", "--json"], capture_output=True, text=True, timeout=60
    )
    payload = json.loads(result.stdout)

    assert payload["tool"] == "thps_p8_launch"
    assert payload["command"] == "check"
    assert payload["schema_version"] == 1
    assert isinstance(payload["clear"], bool)
    assert isinstance(payload["live_instances"], int)

    sweep = payload["sweep"]
    for key in ("supported", "dry_run", "ran", "removed", "bytes", "skipped"):
        assert key in sweep, f"sweep.{key} missing; the GUI's debris state reads it"
    assert sweep["dry_run"] is True, "--check must never delete anything"

    for group in ("game", "launcher"):
        assert isinstance(payload["processes"][group], list)


@needs_launch
def test_check_exit_code_agrees_with_clear() -> None:
    """`--check` used to exit 0 while reporting orphaned segments, so a script
    gating on it saw a clean machine while /dev/shm filled up."""
    result = subprocess.run(
        [str(LAUNCH), "--check", "--json"], capture_output=True, text=True, timeout=60
    )
    payload = json.loads(result.stdout)
    assert result.returncode == (0 if payload["clear"] else 1)


@needs_launch
def test_json_outside_check_is_a_usage_error() -> None:
    result = subprocess.run(
        [str(LAUNCH), "--json", "--launcher-game=/bin/true"],
        capture_output=True,
        text=True,
        timeout=60,
    )
    assert result.returncode == 2
    assert result.stdout == "", "a usage error must not emit a JSON body"
