#!/usr/bin/env python3
"""Assemble NOTICE from the licence files of everything that reaches the user.

    tools/make_notice.py --sdk /path/to/rexglue-sdk > NOTICE

The table below is a judgement about what is in the shipped link line, not a
tree walk. `disasm` is absent on purpose: it is GPL binutils, part of the
recompiler toolchain, and never linked into a shipped binary.
"""

import argparse
import pathlib
import sys
import textwrap

# name, licence, path under the SDK's thirdparty/, optional note
SDK_THIRDPARTY = [
    ("aes_128", "MIT", "aes_128/LICENSE", None),
    ("CLI11", "BSD-3-Clause", "cli11/LICENSE", None),
    ("libtomcrypt (DES)", "public domain / WTFPL", "crypto/des/LICENSE", None),
    ("fmt", "MIT", "fmt/LICENSE", None),
    ("glslang", "BSD-3-Clause and others", "glslang/LICENSE.txt", None),
    ("Dear ImGui", "MIT", "imgui/LICENSE.txt", None),
    ("inja", "MIT", "inja/LICENSE", None),
    ("libmspack", "LGPL-2.1", "libmspack/libmspack/COPYING.LIB", None),
    ("o1heap", "MIT", "o1heap/LICENSE", None),
    ("SDL3", "Zlib", "sdl3/LICENSE.txt", None),
    ("SIMDe", "MIT", "simde/COPYING", None),
    ("Snappy", "BSD-3-Clause", "snappy/COPYING", None),
    ("spdlog", "MIT", "spdlog/LICENSE", None),
    ("SPIRV-Headers", "MIT-like", "spirv-headers/LICENSE", None),
    ("SPIRV-Tools", "Apache-2.0", "spirv-tools/LICENSE", None),
    ("toml++", "MIT", "tomlplusplus/LICENSE", None),
    ("Tracy Profiler", "BSD-3-Clause", "tracy/LICENSE", None),
    ("UTF8-CPP", "Boost-1.0", "utfcpp/LICENSE", None),
    ("volk", "MIT", "volk/LICENSE.md", None),
    ("Vulkan-Headers", "Apache-2.0 / MIT", "vulkan-headers/LICENSE.md", None),
    ("Vulkan Memory Allocator", "MIT", "vulkan-memory-allocator/LICENSE.txt", None),
    ("xxHash", "BSD-2-Clause", "xxHash/LICENSE", None),
    (
        "FFmpeg",
        "LGPL-2.1-or-later",
        "FFmpeg/COPYING.LGPLv2.1",
        "Built with CONFIG_GPL=0 and CONFIG_NONFREE=0, so FFmpeg imposes no GPL\n"
        "obligation on this binary. See docs/RELINKING.md for the LGPL-2.1\n"
        "section 6 relink instructions and the exact fork and commit used.",
    ),
]

LAUNCHER = [
    (
        "RmlUi",
        "MIT",
        "Statically linked, including its Backends/RmlUi_Platform_SDL and\n"
        "Backends/RmlUi_Renderer_SDL sources.",
    ),
    ("SDL3 and SDL3_image", "Zlib", "Linked by the launcher."),
    (
        "FreeType",
        "FTL (FreeType License)",
        "Used under the FreeType License, not the GPL alternative.\n"
        "Portions of this software are copyright (c) The FreeType Project\n"
        "(https://www.freetype.org). All rights reserved.",
    ),
    (
        "Noto Sans (Regular, SemiBold, Bold)",
        "SIL Open Font License 1.1",
        "Shipped as files in assets/ui/fonts/. The OFL requires its notice to\n"
        "travel beside the font files, which assets/ui/fonts/OFL-NOTICE.txt does.",
    ),
]

APP_LOCAL_RUNTIME = [
    (
        "Microsoft Visual C++ Runtime (Windows ZIP only)",
        "Microsoft Software License Terms",
        "Unmodified x64 DLLs copied from Visual Studio 2022's VC\\Redist tree.\n"
        "Redistribution is subject to the Visual Studio license terms and its\n"
        "official REDIST list:\n"
        "https://learn.microsoft.com/visualstudio/releases/2022/redistribution",
    ),
]

HEADER = """\
================================================================================
NOTICE
================================================================================

Third-party software distributed in, or linked into, the binaries in this
release, with the licence texts those licences require to be reproduced.

This project ships no disc image, original game executable, or assets copied
from the disc. Tony Hawk's Project 8 and all associated marks are the property
of their respective owners, who are not affiliated with this project and have
not endorsed it.

Generated by tools/make_notice.py. Do not edit by hand.
"""


def rule(title):
    return f"\n\n{'=' * 80}\n{title}\n{'=' * 80}\n\n"


def read(path):
    try:
        return path.read_text(encoding="utf-8", errors="replace").strip()
    except OSError as exc:
        sys.exit(f"make_notice: cannot read {path}: {exc}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk", type=pathlib.Path, required=True)
    parser.add_argument(
        "--fonts",
        type=pathlib.Path,
        default=pathlib.Path("src/launcher/assets/ui/fonts/OFL-NOTICE.txt"),
    )
    args = parser.parse_args()

    sdk = args.sdk
    if not (sdk / "LICENSE").is_file():
        sys.exit(f"make_notice: no LICENSE at {sdk}; is that a rexglue-sdk tree?")

    third_party = sdk / "thirdparty"
    missing = [n for n, _, rel, _ in SDK_THIRDPARTY if not (third_party / rel).is_file()]
    if missing:
        sys.exit(
            "make_notice: licence text missing for: " + ", ".join(missing) + "\n"
            "Run `git submodule update --init --recursive` in the SDK checkout."
        )

    out = [HEADER]

    out.append(rule("ReXGlue SDK (rexglue-sdk) - BSD-3-Clause"))
    out.append(
        "The runtime this port is built on. Its licence carries two copyright\n"
        "notices, both reproduced below as its terms require: ReXGlue's own, and\n"
        "the Xenia project's, from which it derives.\n\n"
    )
    out.append(read(sdk / "LICENSE"))

    out.append(rule("Bundled with the ReXGlue SDK"))
    for name, licence, rel, note in SDK_THIRDPARTY:
        out.append(f"\n{'-' * 80}\n{name} - {licence}\n{'-' * 80}\n\n")
        if note:
            out.append(textwrap.dedent(note).strip() + "\n\n")
        out.append(read(third_party / rel) + "\n")

    out.append(rule("The launcher's own dependencies"))
    out.append("The launcher is a separate build and links none of the SDK.\n")
    for name, licence, note in LAUNCHER:
        out.append(f"\n{'-' * 80}\n{name} - {licence}\n{'-' * 80}\n\n")
        out.append(textwrap.dedent(note).strip() + "\n")

    if args.fonts.is_file():
        out.append("\n" + read(args.fonts) + "\n")

    out.append(rule("The Windows app-local runtime"))
    for name, licence, note in APP_LOCAL_RUNTIME:
        out.append(f"\n{'-' * 80}\n{name} - {licence}\n{'-' * 80}\n\n")
        out.append(textwrap.dedent(note).strip() + "\n")

    out.append(rule("Not included in this release"))
    out.append(
        "GNU binutils (`disasm` in the SDK tree) is GPL-licensed and belongs to\n"
        "the recompiler toolchain. No binary in this release links it;\n"
        "tools/check_gpl_boundary.sh verifies that on every release build.\n"
    )

    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
